---
- hosts: all
  become: yes
  pre_tasks:
    - name: Disable cloud-init system update on boot
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^ - package-update-upgrade-install'
        line: '# - package-update-upgrade-install'
  tasks:
    - name: Download ec2-metadata script
      get_url:
        url: http://s3.amazonaws.com/ec2metadata/ec2-metadata
        dest: /bin/ec2-metadata
        mode: '0755'
  roles:
    - name: base-packages
    - name: os-tunning

